name: Create Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code in the main branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Git config
      - name: Setup Git
        run: |
          git config --global user.email "dev@healingpaper.com"
          git config --global user.name "ian"

      # Get latest release tag
      - name: Get latest release tag
        id: latest-tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      # Get commit messages since last release
      - name: Get commits since last release
        id: get-commits
        run: |
          echo "::set-output name=commits::$(git log ${{ steps.latest-tag.outputs.tag }}..main --format='* %s (%an)' --reverse)"

      # Update CHANGELOG.md
      - name: Update CHANGELOG.md
        run: |
          echo "## Changes since last release" >> CHANGELOG.md
          echo "${{ steps.get-commits.outputs.commits }}" >> CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md with new commits"

      # Push changes
      - name: Push changes
        run: git push origin main

      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          destination_branch: "main"
          title: "Release PR"
          body: |
            This PR includes the changes for the next release.
            ### Commits:
            ${{ steps.get-commits.outputs.commits }}
          token: ${{ secrets.GITHUB_TOKEN }}
