name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  update-changelog-and-create-release-pr:
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: create release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "9"

      - name: Install Dependencies with pnpm
        run: pnpm install

#      - name: Update Changelog
#        run: pnpm run update-changelog

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: "chore(release): version packages 🦋"
#          publish: pnpm publish:packages
#          version: pnpm version:packages
          commit: "chore(release): version packages 🦋 [skip ci]"
#        with:
#          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  publish:
#    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
#    needs: update-changelog-and-create-release-pr
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Repo
#        uses: actions/checkout@v3
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20.x'
#          registry-url: 'https://registry.npmjs.org'
#
#      - name: Install Dependencies with pnpm
#        run: pnpm install
#
#      - name: Publish to npm
#        run: pnpm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
