name: Create Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code in the main branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Git config
      - name: Setup Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      # Get latest release tag and write to environment file
      - name: Get latest release tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      # Install dependencies (assumes lerna-changelog is part of devDependencies)
      - name: Install dependencies
        run: npm install

      # Generate changelog from the latest tag to HEAD and write to environment file
      - name: Generate changelog
        run: |
          echo "CHANGELOG=$(npx lerna-changelog --tag-from=$LATEST_TAG --next-version Unreleased)" >> $GITHUB_ENV

      # Print changelog (optional, for debug purposes)
      - name: Print changelog
        run: echo "$CHANGELOG"

      # Push changes
      - name: Push changes
        run: git push origin main

      # Create Pull Request with changelog in the body
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          delete-branch: true
          title: "Release PR"
          branch: release-pr
          body: ${{ env.CHANGELOG }}
          token: ${{ secrets.GITHUB_TOKEN }}
