name: Create Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code in the main branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Git config
      - name: Setup Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      # Get latest release tag
      - name: Get latest release tag
        id: latest-tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      # Install dependencies (assumes lerna-changelog is part of devDependencies)
      - name: Install dependencies
        run: npm install

      # Generate changelog from the latest tag to HEAD
      - name: Generate changelog
        id: changelog
        run: echo "::set-output name=changelog::$(npx lerna-changelog --tag-from=${{ steps.latest-tag.outputs.tag }} --next-version Unreleased)"

      # Print changelog (optional, for debug purposes)
      - name: Print changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"

      # Push changes
      - name: Push changes
        run: git push origin main

      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          delete-branch: true
          title: "Release PR"
          branch: release-pr
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
